### ISSUE TITLE
Update provided functionality

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp-recipe-search#2]
At current the recipe does not use the `public` folder by default, nor does it render a search bar in the `starter` theme, if one installs it. This latter point is probably in the wrong place, but it would be nice to take a moment to figure out where it actually belongs (i.e. more of a note to self).
Should this recipe even have a public dir? I cannot remember how the system works on knowing when to and when not to install/use a public dir.

**Comment by robbieaverill** [comment]
@NightJar could you follow up on this with some action points and triaging when you have a minute please?

**Comment by NightJar** [comment]
Action points:
1. [ ] add a public dir to the recipe and increase requirement of `silverstripe/framework` to 4.1 (if necessary)
2. [ ] update the requirement of `silverstripe/fulltextsearch` to it's next release, which will include https://github.com/silverstripe/silverstripe-fulltextsearch/pull/216

**Comment by robbieaverill** [comment]
I'm not 100% sure on what you mean here - CWP 2.0 is SS 4.1 which does use the public dir right?

The fulltextsearch requirements will be updated in the next CWP 2.1 release which I'm assembling at the moment :)

**Comment by NightJar** [comment]
Yeah, I'm relatively confident that CWP 2.1 will close this issue.

**Comment by robbieaverill** [comment]
Cool. Do you think its worth raising issues in recipes when they have new features to include? It could either be that we do it that way, or that its part of our recipe preparation process. I'd probably be in favour of the latter - what do you think?

**Comment by NightJar** [comment]
Yeah, no `public` folder by default. As I recall it TractorCow advised me that if a public folder is present, it will be used. If not, one will not be created (as a backwards compatible thing for 4.0.x)

But now thinking about it - for the very reason parenthesised above, this should not be implmented. It should be up to the developer on any upgrade whether or not to use the public dir (which while it is mandatory for the context of CWP to which it is vendored, isn't necessarily where this recipe might be employed).

What do you think?

```
[~/work/recipepublictest]$ cat > composer.json << COMPOSER
{
    "name": "test/test",
    "require": {
        "cwp/cwp-recipe-search": "^2"
    }
}
COMPOSER

[~/work/recipepublictest]$ composer install
```
***
```
[~/work/recipepublictest]$ ls
composer.json  composer.lock  index.php  install.php  install-frameworkmissing.html  mysite/  resources/  vendor/  web.config

[~/work/recipepublictest]$ cat composer.json
{
    "name": "test/test",
    "require": {
        "cwp/cwp-recipe-search": "^2"
    },
    "extra": {
        "project-files-installed": [
            "mysite/.htaccess",
            "mysite/_config.php",
            "mysite/_config/environmentcheck.yml",
            "mysite/_config/mysite.yml",
            "mysite/code/Page.php",
            "mysite/code/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ]
    }
}

[~/work/recipepublictest]$
```

**Comment by robbieaverill** [comment]
This recipe is specific to CWP and requires at least CWP 2.0 which enforces a mandatory public webroot, or at least requires one for our support. You've obviously got a better idea of what you want here though so I'll leave it to you to prioritise :)

**Comment by NightJar** [comment]
Yeah, the question now...

Given:
1. This recipe is CWP specific
2. CWP _requires_ a `public` web root
3. CWP requires at least `cwp/cwp-recipe-core`
4. `cwp/cwp-recipe-core` includes a `public` folder

... moot.
