### ISSUE TITLE
Unable to install: Composer conflict with cwp-search

### ISSUE THREAD

**Issue by phptek** [silverstripe/cwp-recipe-search#3]
This module depends on `silverstripe/fulltextsearch` 3.2@stable which depends on `cwp-search` which itself depends on `silverstripe/fulltetxsearch` ^3. If `cwp-recupe-search` module is including cwp-search, then the fulltextsearch dependency should be omitted, otherwise the usual Composer conflict applies (and you guys need to maintain at least 2 refs to the same package).

## composer.json snippet
```
  7     "require": {
  8         "php": ">=5.6",
  9         "cwp/cwp-recipe-search": "2.0.0-rc2",
 10         "silverstripe/recipe-form-building": "1.x-dev",
 11         "silverstripe/recipe-authoring-tools": "1.x-dev",
```
## Composer Error

```
  Problem 1
    - cwp/cwp-search 1.0.0-rc1 requires silverstripe/fulltextsearch 3.0.0-rc1 -> satisfiable by silverstripe/fulltextsearch[3.0.0-rc1].
    - Can only install one of: silverstripe/fulltextsearch[3.2.0, 3.0.0-rc1].
    - cwp/cwp-recipe-search 2.0.0-rc2 requires cwp/cwp-search 1.0.0-rc1 -> satisfiable by cwp/cwp-search[1.0.0-rc1].
    - cwp/cwp-recipe-search 2.0.0-rc2 requires silverstripe/fulltextsearch 3.2.0@stable -> satisfiable by silverstripe/fulltextsearch[3.2.0].
    - Installation request for cwp/cwp-recipe-search 2.0.0-rc2 -> satisfiable by cwp/cwp-recipe-search[2.0.0-rc2].
```

**Comment by robbieaverill** [comment]
This was a bug in the release process which we've resolved now. Cow shouldn't set specific constraints for modules, only for recipes. This will be resolved in CWP 2.0.0-rc3. Reference issue: https://github.com/silverstripe/cow/pull/79
