### ISSUE TITLE
Using fulltextsearch POST store does not work with CWP

### ISSUE THREAD

**Issue by brettt89** [silverstripe/cwp-recipe-search#8]
With the release of 2.3.0 an 2.3.1, a move was made to use the built-in POST index store of fulltextsearch.

However CWP does not work with this version of the POST store due https://github.com/silverstripe/silverstripe-fulltextsearch/issues/260

`remotepath` is not set or used in CWP so is breaking `Solr_Configure` on CWP environments.

This previously wasn't a problem in 2.2.x as we were using the CWP defined POST index store instead which validates if this is actually set before trying to assign.

https://github.com/silverstripe/cwp-search/blob/master/src/Solr/CwpSolrConfigStore.php

**Comment by brettt89** [comment]
Specifically this looks to have been caused by this commit

https://github.com/silverstripe/cwp-search/commit/068096c28a353bd0f0952d43ba5f6c7b06e7b176

This enforced `post` as the Index Store. Unfortunately it doesn't look like we can override this or workaround it easily.

**Comment by NightJar** [comment]
Related context: https://github.com/silverstripe/cwp-search/pull/18

**Comment by brynwhyman** [comment]
The following (merged) PR re-implements CWP support in the fulltextsearch module: https://github.com/silverstripe/silverstripe-fulltextsearch/pull/261

**Comment by brynwhyman** [comment]
This was resolved but the issue was never closed.
